[gcp_service_account]
type = "service_account"
project_id = "grand-song-463316-p3"
private_key_id = "0d54d60719e43bc5b58dbdb9f06d19bcc5175c6f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCtr6DIoeeQc2ZR
B0/x6dh13IBDkIR/c2FrSmh9h/7ZJKHyH99Hg4pjl1YpUovSSmz0NY7br4SueX/X
ZIzkM0kHyikja95WhuyXpUjVYFp9uX34iLLt81zwjN1CQBpiIuk/bLJMsjEuU8nR
2AI/1mL+ZvidzKfosjAjGUaOi02TfGVFcys3kJF2XUIWfNovgpWRMfHvF/9t+Z4e
L/qYqvXgAOzHd2v2yzTrnvNIW2IBVmh+QF2d5N52TlhDHWHLTBDzM8n++gRWMA5p
yFGWOeSc7ueUK4yQSqyQK3nQxclO930l1teaztDRu1L484K7A8tLMUTmzoEFXQd4
lKwVxkjTAgMBAAECggEAB9mvKz0CJz8dX0k00wAuUU7I71ovWvFfSbGrHQ1nYUTX
cFxXbmHi1eiHs5twXW4RaaJSwC7j5jJGAHl3fXMB+IZUgK4woPmSj7If+MuqRhIl
wEoxctwz6wglkgfYCW/UL2fde+ZL9HDuEibbcdY3Uuda57WnMIx+l3+IzGA90+N8
D2FQzsQJtog6LK0HdwlOI2CRcHMpxJS4i7pxdxvvoK60hz7o7goUdINDMIlv2dLR
vay3PXePugmU/xOc8rtp/j6RT6KwAkXWDmKepzEZHEWV+ZJvsa3KNt4LqFQ6WWGW
2ZXo08GWDk6I7PB8v9kcQk3l5XsMfefyZ3eT/oPk+QKBgQDzrrDq1dZ1KDybrY/U
mwcv2TBr9gAmzpSH/K2+6RAlpuJhC2+ubHkIsrmqdt5s25JBAmYiwj7HdKtclrKZ
jDOoFvNTGF79HlW6I6Ab+LeqWFiPyNGEb2/L7u3gi5d3z6S09XlrFDPKuWVgPQbh
jn2pwM8R8cUNFhQ9lX5BwYRdqQKBgQC2dyrdbzyciWtF5dyh5kl8vBuNdiOCR3XQ
EynVkogngBZU8kfSi6jicAd9lSddd3b1VH2MYeym74wqGQ5ZtcuPVXSD54NdU/Qr
jLEoexcuRC5w30tYekLeRLdsrBtC0yUSq67QNw97HxGjrGeM4PHOGzcg57uEEilR
cwbn3X4oGwKBgQDAkGKUIMlpKZPDfgM0AhJK2HmwRuTVxdeQIrf2LlypNFieUZg+
oM+AdSPNNkQMh/LqVof5ncBYg7TK5Pdb6XQEt6YvGwotQeSCxJZIpGIXRdsuPIZ8
/ka9RCFMmWLntfm1WmpJmNxYresTgwZGBgD9vTSlPIX4EmOKSvFL6y27iQKBgAhg
pk4uakkBojQ+Xofsa9lXRaiUEQNNRqJ8DsKojKnLnrrduOB42xMyc5WXgIwxDPws
mesVH+l2PCg+qEMELslw8f2QZp6lWSOavROPuzu7k6pJBkuUqXdNDmLl8AZ8bUpT
KZ6TuJk9jvDF3KdCOLfu1fQjz587ujvsHRgOOlmbAoGALKB2QAsqAVD3bjHgY6mW
EO4+xMn2EeDT875vw7ru/QEc5F9Wp5DQOyztpzPhy4h9guz2PA8d1bJKJaEh6k9K
c41Y8B8i8c+yCo/HmoBxzUeWMbDxV76sABvTMe09Re047C2TZh44CMgEEK2Io8RY
KPbdxc54hA5LHXSZfAKKOzo=
-----END PRIVATE KEY-----"""
client_email = "hyojooproject@grand-song-463316-p3.iam.gserviceaccount.com"
client_id = "107642895930977802455"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hyojooproject@grand-song-463316-p3.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
